export const categories = [
  {
    id: 1,
    name: "Aluminium Incense Holders",
    slug: "aluminium-incense-holders",
    image: "/categories/aluminium-incense.webp",
    description: "Lightweight and durable holders for your incense.",
    isHighlighted: true,
  },
  {
    id: 2,
    name: "Brass Incense / Fragrance Burners",
    slug: "brass-incense-fragrance-burners",
    image: "/categories/brass-incense.jpg",
    description: "Elegant brass burners for sacred rituals.",
    isHighlighted: true,
  },
  {
    id: 3,
    name: "T-Light Holders / Incense Burners",
    slug: "t-light-holders-incense-burners",
    image: "/categories/tlight.webp",
    description: "Illuminate your space with decorative T-light holders.",
    isHighlighted: true,
  },
  {
    id: 4,
    name: "Wooden Incense Holders / Grids",
    slug: "wooden-incense-holders-grids",
    image: "/categories/incenseburner.jpg",
    description:
      "Eco-friendly wooden holders for a natural incense experience.",
    isHighlighted: true,
  },
  {
    id: 5,
    name: "Incense Accessories",
    slug: "incense-accessories",
    image: "/categories/incense-accessories.jpg",
    description: "Essential tools to complement your incense rituals.",
    isHighlighted: true,
  },
  {
    id: 6,
    name: "Altar Tables",
    slug: "altar-tables",
    image: "/categories/altar-table.jpg",
    description: "Sacred wooden and metal tables for your rituals.",
    isHighlighted: false,
  },
  {
    id: 7,
    name: "Altar Tools",
    slug: "altar-tools",
    image: "/categories/tools.jpg",
    description: "Spiritual tools to enhance your sacred practices.",
    isHighlighted: false,
  },
  {
    id: 8,
    name: "Offering Bowls",
    slug: "offering-bowls",
    image: "/categories/bowls.jpg",
    description: "Handcrafted bowls for offerings and blessings.",
    isHighlighted: false,
  },
  {
    id: 9,
    name: "Cauldrons",
    slug: "cauldrons",
    image: "/categories/cauldron.jpg",
    description: "Traditional cast-iron cauldrons for rituals and incense.",
    isHighlighted: false,
  },
  {
    id: 10,
    name: "Brass Grids / Altar Grids",
    slug: "brass-grids-altar-grids",
    image: "/categories/altar-grids.jpg",
    description: "Sacred geometry grids for spiritual energy work.",
    isHighlighted: false,
  },
  {
    id: 11,
    name: "Copper Bracelets",
    slug: "copper-bracelets",
    image: "/categories/bracelet.jpeg",
    description: "Copper bracelets known for their healing properties.",
    isHighlighted: false,
  },
  {
    id: 12,
    name: "Copper Grids",
    slug: "copper-grids",
    image: "/categories/coppergrid.png",
    description: "Energy-enhancing copper grids for rituals.",
    isHighlighted: false,
  },
  {
    id: 13,
    name: "Herb Grinders",
    slug: "herb-grinders",
    image: "/categories/herb-grinder.jpg",
    description: "Efficient grinders for herbs and incense preparation.",
    isHighlighted: false,
  },
  {
    id: 14,
    name: "Lanterns",
    slug: "lanterns",
    image: "/categories/lantern.avif",
    description: "Beautiful lanterns to create a warm ambiance.",
    isHighlighted: false,
  },
  {
    id: 15,
    name: "Wooden Wall Hangings",
    slug: "wooden-wall-hangings",
    image: "/categories/wooden-wall-hangings.jpg",
    description: "Artistic wooden decor to adorn your sacred space.",
    isHighlighted: false,
  },
  {
    id: 16,
    name: "Metal Wall Hangings",
    slug: "metal-wall-hangings",
    image: "/categories/metal-wall-hangings.jpg",
    description: "Intricate metal artwork to enhance your walls.",
    isHighlighted: false,
  },
  {
    id: 17,
    name: "Singing Bowls",
    slug: "singing-bowls",
    image: "/categories/singing-bowl.jpg",
    description: "Harmonize your space with calming sound vibrations.",
    isHighlighted: false,
  },
  {
    id: 18,
    name: "Storage Shelves",
    slug: "storage-shelves",
    image: "/categories/storage-shelves.jpg",
    description: "Organize your spiritual tools and accessories.",
    isHighlighted: false,
  },
  {
    id: 19,
    name: "Ting Shas (Tibetan Cymbals)",
    slug: "ting-shas-tibetan-cymbals",
    image: "/categories/tingsha.jpg",
    description: "Traditional cymbals used for meditation and sound healing.",
    isHighlighted: false,
  },
  {
    id: 20,
    name: "Trinkets / Storage Dishes",
    slug: "trinkets-storage-dishes",
    image: "/categories/trinket.jpg",
    description: "Decorative dishes for storing small sacred items.",
    isHighlighted: false,
  },
];
